# Generated by Django 3.0.5 on 2020-04-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('experience', models.CharField(max_length=30)),
                ('institute', models.CharField(max_length=30)),
                ('education', models.CharField(max_length=30)),
                ('employer', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=30)),
                ('score', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('stringId', models.CharField(db_index=True, max_length=30)),
                ('questions', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('q', models.CharField(max_length=30)),
                ('options', models.CharField(max_length=30)),
                ('tagId', models.CharField(max_length=30)),
                ('expected1', models.CharField(max_length=30)),
                ('expected2', models.CharField(max_length=30)),
            ],
        ),
    ]
