# Generated by Django 3.0.5 on 2020-05-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_person_reminderscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='reminderscount',
            field=models.IntegerField(default=0),
        ),
    ]
